#!/bin/bash

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
    echo "Direkte Commits in den Main-Branch sind nicht erlaubt. Bitte erstelle einen Zweig für deine Änderungen."
    exit 1
fi
